### ISSUE TITLE
FR: Support TypeScript arrays with minimum length (`+`)

### ISSUE THREAD

**Issue by thiagowfx** [jrandolf/cddlconv#1]
Goal: https://stackoverflow.com/questions/49910889/typescript-array-with-minimum-length

Why? For example, in [WebDriver BiDi network intercepts](https://pr-preview.s3.amazonaws.com/w3c/webdriver-bidi/pull/429.html#command-network-addIntercept):

```cddl
network.AddIntercept = {
  method: "network.addIntercept",
  params: network.AddInterceptParameters
}

network.AddInterceptParameters = {
  phases: [+network.InterceptPhase],
  ?urlPatterns: [*text],
}
```

...`phases` should contain at least one element as per https://datatracker.ietf.org/doc/rfc8610/ (sections 3.4 and 3.2).

Currently, the generated TS file looks as follows:

```
export namespace Network {
  export type AddInterceptParameters = {
    phases: [...Network.InterceptPhase[]];
    urlPatterns?: [...string[]];
  };
}
```

...it allows empty arrays c.f. [ersatz](http://ersatz/?v1=XYw7CoAwEAWvElIvES0sFO9gv75CJEhAV8muoLf3UwrDVMNwRfwAKqkEcf2Z2RfrmCSYevLx3Ldszq49uiMv%2FWgWs6jrHIcQ1HKSmYF2kEGmTdTeSpt%2Fi9YDzxy4AQ%3D%3D) example.

**Comment by jrandolf** [comment]
Fixed in https://github.com/anweiss/cddl/issues/193
