### ISSUE TITLE
Don't emit EsLint banned types

### ISSUE THREAD

**Issue by Lightning00Blade** [jrandolf/cddlconv#4]
Like the name suggest Typescript EsLint exports some types that should be banned.
Currently if a CDDL has no members it will produce `{}` this brakes type-checking as this implies anything.
The correct output should be `Record<string,never>`.

Example CDDL that that happens to: 
```
NetworkCommand = (
)
```

While one could introduce a EsLint rule to patch this on their own it feels that the change should be made to the parser.

**Comment by jrandolf** [comment]
Generated files should never be linted (in any language). They should be thought of as temporary artifacts. Similar to `protobuf` and other code generators.
